version: '3.8'

services:
  api:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: visionsearch-api
    ports:
      - "8000:8000"

    environment:

      IMG_DIR: /shared/images
      AWS_REGION: us-east-1
      HNSW_DIM: 512
      HNSW_MAX_ELEMENTS: 100000
      HNSW_SPACE: cosine
      HNSW_EF_CONSTRUCTION: 200
      HNSW_M: 16
      HNSW_EF_SEARCH: 50 
      CLIP_ENDPOINT_NAME: clip-multimodal-endpoint


      HF_API_TOKEN:          ${HF_TOKEN}
      AWS_ACCESS_KEY_ID:     ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      SAGEMAKER_ROLE_ARN:    ${SAGEMAKER_ROLE_ARN}
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    command:
      - uvicorn
      - server.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
